services:
  app:
    container_name: go_local
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "80:8080"
#    volumes:
#      - ./src:/app
    networks:
      - go-production

networks:
  go-production: